[build]
  command = "bun run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "bun astro dev --host 0.0.0.0"
  framework = "#custom"
  port = 8888
  targetPort = 4321

[dev.environment]
  VITE_APP_URL = "http://localhost:8888"

[context.production.environment]
  VITE_APP_URL = "https://mindshare.quip.network"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
